services:
  postgres:
    image: postgres:16
    container_name: veterinaria-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: veterinaria
      POSTGRES_USER: veterinaria_user
      POSTGRES_PASSWORD: veterinaria_password

    ports:
      - "5432:5432"

    volumes:
      - veterinaria_postgres_data:/var/lib/postgresql/data

volumes:
  veterinaria_postgres_data: