apiVersion: v1
kind: ConfigMap
metadata:
  name: veterinaria-api-config
data:
  DATABASE_HOST: "veterinaria-db.c1csk6cksydj.us-east-2.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "veterinaria"
  DATABASE_SCHEMA: "schema_production"