apiVersion: v1
kind: ConfigMap
metadata:
  name: veterinaria-api-config
data:
  DATABASE_HOST: "veterinaria-db.c1csk6cksydj.us-east-2.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "veterinaria"
  DATABASE_SCHEMA: "schema_production"

  AWS_REGION: "us-east-2"
  SQS_QUEUE_URL: "https://sqs.us-east-2.amazonaws.com/634197800511/veterinaria-api-queue"