apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
data:
  AWS_REGION: "us-east-2"

  SQS_QUEUE_URL: "https://sqs.us-east-2.amazonaws.com/634197800511/veterinaria-api-queue"

  AWS_API_URL: "http://ae7646e6cf2b74912906f40f9a30539d-032ee795ec92fbaf.elb.us-east-2.amazonaws.com"

  AWS_API_METRICS_URL: "http://ae7646e6cf2b74912906f40f9a30539d-032ee795ec92fbaf.elb.us-east-2.amazonaws.com/metrics"

  GCP_API_METRICS_URL: "http://34.10.12.227/metrics"

  AZURE_API_METRICS_URL: "http://57.169.3.252/metrics"
