apiVersion: apps/v1
kind: Deployment
metadata:
  name: veterinaria-orchestrator
  labels:
    app: veterinaria-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veterinaria-orchestrator
  template:
    metadata:
      labels:
        app: veterinaria-orchestrator
    spec:
      serviceAccountName: veterinaria-api-sqs
      containers:
        - name: orchestrator
          image: 634197800511.dkr.ecr.us-east-2.amazonaws.com/veterinaria-api:orchestrator-v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: orchestrator-config
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /orchestrator/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /orchestrator/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
